# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Swaraj Dhumne
tagline:             'An up and coming web dev'
description:         "I'm just a web developer. My goal is to make the process of developing for the web a quick and painless one, as well as one which allows the product to be fast and robust."
url:                 http://swarajd.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Swaraj Dhumne
  url:               https://github.com/swarajd/
  email:             swaraj.dhumne@gmail.com

# Custom vars
version:             1.0.0